targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/models/*.dart
          - lib/**/cubit/*.dart
      json_serializable:
        generate_for:
          - lib/**/models/*.dart
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/**/screens/*_screen.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/core/router/router.dart
