import 'package:weather_app/weather/domain/entities/place.dart';

/// Cities spread across climates and time zones, for the Explore page to
/// draw from. `country` holds the full name here because the page shows it.
const worldCities = <Place>[
  Place(name: 'Tokyo', country: 'Japan', latitude: 35.68, longitude: 139.69),
  Place(
    name: 'Reykjavik',
    country: 'Iceland',
    latitude: 64.15,
    longitude: -21.94,
  ),
  Place(name: 'Cairo', country: 'Egypt', latitude: 30.04, longitude: 31.24),
  Place(
    name: 'Sydney',
    country: 'Australia',
    latitude: -33.87,
    longitude: 151.21,
  ),
  Place(
    name: 'New York',
    country: 'United States',
    latitude: 40.71,
    longitude: -74.01,
  ),
  Place(
    name: 'Rio de Janeiro',
    country: 'Brazil',
    latitude: -22.91,
    longitude: -43.17,
  ),
  Place(
    name: 'Cape Town',
    country: 'South Africa',
    latitude: -33.92,
    longitude: 18.42,
  ),
  Place(name: 'Mumbai', country: 'India', latitude: 19.08, longitude: 72.88),
  Place(
    name: 'London',
    country: 'United Kingdom',
    latitude: 51.51,
    longitude: -0.13,
  ),
  Place(name: 'Paris', country: 'France', latitude: 48.86, longitude: 2.35),
  Place(
    name: 'Singapore',
    country: 'Singapore',
    latitude: 1.35,
    longitude: 103.82,
  ),
  Place(
    name: 'Dubai',
    country: 'United Arab Emirates',
    latitude: 25.2,
    longitude: 55.27,
  ),
  Place(name: 'Nairobi', country: 'Kenya', latitude: -1.29, longitude: 36.82),
  Place(
    name: 'Vancouver',
    country: 'Canada',
    latitude: 49.28,
    longitude: -123.12,
  ),
  Place(
    name: 'Buenos Aires',
    country: 'Argentina',
    latitude: -34.6,
    longitude: -58.38,
  ),
  Place(
    name: 'Istanbul',
    country: 'Türkiye',
    latitude: 41.01,
    longitude: 28.98,
  ),
  Place(
    name: 'Seoul',
    country: 'South Korea',
    latitude: 37.57,
    longitude: 126.98,
  ),
  Place(
    name: 'Bangkok',
    country: 'Thailand',
    latitude: 13.76,
    longitude: 100.5,
  ),
  Place(
    name: 'Mexico City',
    country: 'Mexico',
    latitude: 19.43,
    longitude: -99.13,
  ),
  Place(name: 'Lima', country: 'Peru', latitude: -12.05, longitude: -77.04),
  Place(name: 'Oslo', country: 'Norway', latitude: 59.91, longitude: 10.75),
  Place(
    name: 'Auckland',
    country: 'New Zealand',
    latitude: -36.85,
    longitude: 174.76,
  ),
  Place(
    name: 'Honolulu',
    country: 'United States',
    latitude: 21.31,
    longitude: -157.86,
  ),
  Place(
    name: 'Marrakesh',
    country: 'Morocco',
    latitude: 31.63,
    longitude: -7.99,
  ),
  Place(
    name: 'Ulaanbaatar',
    country: 'Mongolia',
    latitude: 47.89,
    longitude: 106.91,
  ),
  Place(name: 'Havana', country: 'Cuba', latitude: 23.11, longitude: -82.37),
  Place(name: 'Lagos', country: 'Nigeria', latitude: 6.52, longitude: 3.38),
  Place(name: 'Rome', country: 'Italy', latitude: 41.9, longitude: 12.5),
  Place(
    name: 'Anchorage',
    country: 'United States',
    latitude: 61.22,
    longitude: -149.9,
  ),
  Place(
    name: 'Ushuaia',
    country: 'Argentina',
    latitude: -54.8,
    longitude: -68.3,
  ),
  Place(name: 'Lisbon', country: 'Portugal', latitude: 38.72, longitude: -9.14),
  Place(name: 'Hanoi', country: 'Vietnam', latitude: 21.03, longitude: 105.85),
  Place(
    name: 'Tashkent',
    country: 'Uzbekistan',
    latitude: 41.3,
    longitude: 69.24,
  ),
  Place(
    name: 'Addis Ababa',
    country: 'Ethiopia',
    latitude: 9.03,
    longitude: 38.74,
  ),
  Place(
    name: 'Perth',
    country: 'Australia',
    latitude: -31.95,
    longitude: 115.86,
  ),
  Place(name: 'Kathmandu', country: 'Nepal', latitude: 27.72, longitude: 85.32),
];
